services:
  server:
    image: deminy/swoole-by-examples:server-6.0
    environment:
      AUTORELOAD_PROGRAMS: "apcu-caching ddos-protection http1 http1-integrated http2 interruptible-sleep keepalive mixed-protocols-1 pool-msgqueue pool-tcp-socket pool-unix-socket redis rock-paper-scissors tcp1 tcp2 udp websocket websocket-integrated"
      DISABLE_DEFAULT_SERVER: 1
    ports:
      - 9801:9801
    volumes:
      - ./examples:/var/www
  client:
    image: deminy/swoole-by-examples:client-6.0
    environment:
      DISABLE_DEFAULT_SERVER: 1
    links:
      - mysql
      - postgresql
      - server
    volumes:
      - ./examples:/var/www
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
