[supervisord]
user = root

[program:mixed-protocols-per-port]
command = /var/www/examples/servers/mixed-protocols-per-port.php
user = root
autostart = true
autorestart = true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/1
stderr_logfile_maxbytes=0
