name: Build Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'deminy/swoole-by-examples' }}
    strategy:
      fail-fast: false
      matrix:
        type: ["server", "client"]
        version: ["5.1", "6.0"]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./dockerfiles/${{ matrix.type }}/
          build-args: |
            SWOOLE_VERSION=${{ matrix.version }}
            PHP_VERSION=8.3
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: deminy/swoole-by-examples:${{ matrix.type }}-${{ matrix.version }}
