name: Code Quality

on: [ push, pull_request, workflow_dispatch ]

jobs:
  checks:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Coding Style Checks
        run: docker run -q --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php8.3-alpine php-cs-fixer fix -q --dry-run

      - name: Run Static Analysis
        run: |
          docker run -q --rm -v "$(pwd):/project" -w /project phpswoole/swoole:6.2 bash -c '
            set -e
            echo "swoole.enable_library=Off" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
            composer global require -n -q --no-progress -- \
              phpstan/phpstan=~2.0 \
              predis/predis=~3.0 \
              swoole/library=~6.2
            ~/.composer/vendor/bin/phpstan analyse --no-progress --memory-limit 2G
          '
